name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Login started"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Login finshed"

    - name: Build Docker image
      run: |
        docker build -t rgluis/docker-graphql:0.0.2 .
        docker build -t rgluis/docker-graphql:latest .

    - name: Push Docker image
      run: |
        docker push rgluis/docker-graphql:0.0.2
        docker push rgluis/docker-graphql:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
